---
title: Typst CSS
---

The Typst CSS feature translates CSS properties into Typst properties, to allow similar styling between the HTML formats and the Typst format.

It is tuned for two use-cases:

- HTML Tables styled by table packages
- HTML `<pre>` tags representing console output with spans decorated with colors, e.g. from ANSI.

This document is oriented to
* package developers who want to produce `table` or `pre` output which can be translated to Typst
* extension developers who want to improve the translation of CSS properties, or add other CSS properties

It describes how Typst CSS works, how to enable and disable this feature and `pre` tag processing

## How Typst CSS works

Unless table processing is disabled with `html-table-processing="none"`, tables in HTML raw blocks will be parsed into the Pandoc AST and then written by the output format. 

See the below section for information on `pre` tags, which are opt-in but work the same way.

When the output format is Typst, Quarto will [`juice`](https://github.com/Automattic/juice) the HTML input, annotating the HTML elements with CSS properties from the rules in any style sheets included in the HTML raw block.

A Quarto post-processing filter translates the HTML attributes and CSS properties into attributes of the form `typst:property` or `typst:text:property`, and the Typst writer in Pandoc writes the output appropriately.

## Supported Elements and Properties

Typst CSS works for the specific combinations of HTML elements and CSS properties below:

|                  | span | div | table | td  |
|------------------|------|-----|-------|-----|
| background-color |   ✓  |     |       |  ✓  |
| border[^1]       |      |     |       |  ✓  |
| color            |   ✓  |     |       |  ✓  |
| font-family      |      |  ✓  |   ✓   |     |
| font-size        |      |  ✓  |   ✓   |     |
| opacity          |   ✓  |     |       |  ✓  |
| align[^2]        |      |     |       |  ✓  |


[^1]: `border`, `border-left` etc, `border-width`, `border-style`, `border-color`, `border-left-width` etc

[^2]: `text-align`, `vertical-align`

## Disabling Typst CSS

The CSS-to-Typst Lua filter operates over the entire AST (not just tables and pre-tags). For troubleshooting purposes, the filter can be disabled with:

``` yaml
format:
  typst:
    css-property-processing: none
```
    

## `pre` tag processing

`pre`-tag processing is intended for automatic translation of ANSI to Typst via HTML. Quarto does not currently capture ANSI output from execution, but this feature is available for packages and extensions.

`pre` tag processing is opt-in with `html-pre-tag-processing="parse"` on div directly enclosing the HTML raw block:

```` markdown
::: {html-pre-tag-processing="parse"}

```{=html}
<pre>...</pre>
```
:::
````

## Modifying the translation

You can add your own Lua filters to add or change the translation of CSS properties into Typst properties.

Consult the Pandoc documentation for Typst property attribute output:

<https://pandoc.org/typst-property-output.html>

and the source of the Lua filter which translates properties:

<https://github.com/quarto-dev/quarto-cli/blob/main/src/resources/filters/quarto-post/typst-css-to-props.lua>

If your filter runs before the Typst CSS Lua filter and removes CSS properties, it can override the filter's behavior (untested). If it adds support for other CSS properties, it can run before or after the built-in filter.